---
apiVersion: v1
kind: Service
metadata:
  name: front-end1
  labels:
    name: front-end1
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end1
